name: Sphinx-Update

on:
  push:
    branches: [ main ]

jobs:
  sphinx-update:
    name: Update Sphinx docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Regen Sphinx .rst files
        run: |
          pip install sphinx
          cd ./docs
          sphinx-apidoc -f -o ./source ../kiri
      - name: Commit files
        id: commit
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          set +e
          git commit -m "Docs Update [auto]" -a
          set -e
      - name: Push to main
        if: steps.commit.outputs.exit_code == 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
